name: release-pybamm-param

on:
  push:
    branches:
      - main

jobs:

  make_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install standard python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install nox
        python -m pip install .

    - name: Assert new version is greater than current tag
      run: |
        python -c "import pybamm; assert pybamm.__version__ > {{ github.ref }}"

    - name: Release
      run: |
        nox -s release